/**
 * ControlInput.cs - Input Enumeration
 *
 * This source-code is part of rzxe - an experimental game engine by Oddmatics:
 * <<https://www.oddmatics.uk>>
 *
 * Author(s): Rory Fewell <roryf@oddmatics.uk>
 */

namespace Oddmatics.Rzxe.Input
{
    /// <summary>
    /// Specifies constants defining possible inputs into the game engine from the
    /// user's control method.
    /// </summary>
    public enum ControlInput : int
    {
        Anything = -1,
        
        
        MouseButton1 = 0,
        MouseButton2,
        MouseButton3,
        MouseButton4,
        MouseButton5,
        MouseButton6,
        MouseButton7,
        MouseButton8,
        MouseButton9,
        
        MouseButtonLeft = 0,
        MouseButtonRight,
        MouseButtonMiddle,
        
        
        Spacebar   = 32,
        Apostrophe = 39,
        Comma      = 44,
        Minus,
        Period,
        ForwardSlash,
        Digit0,
        Digit1,
        Digit2,
        Digit3,
        Digit4,
        Digit5,
        Digit6,
        Digit7,
        Digit8,
        Digit9,
        Semicolon = 59,
        Equals    = 61,
        A         = 65,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftSquareBracket,
        Backslash,
        RightSquareBracket,
        GraveAccent = 96,
        Escape = 256,
        Enter,
        Tab,
        Backspace,
        Insert,
        Delete,
        Right,
        Left,
        Down,
        Up,
        PageUp,
        PageDown,
        Home,
        End,
        CapsLock = 280,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        F1 = 290,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        F25,
        Keypad0 = 320,
        Keypad1,
        Keypad2,
        Keypad3,
        Keypad4,
        Keypad5,
        Keypad6,
        Keypad7,
        Keypad8,
        Keypad9,
        KeypadDecimal,
        KeypadDivide,
        KeypadMultiply,
        KeypadSubtract,
        KeypadAdd,
        KeypadEnter,
        KeypadEquals,
        LeftShift = 340,
        LeftControl,
        LeftAlt,
        LeftSuper,
        RightShift,
        RightControl,
        RightAlt,
        RightSuper,
        Menu,
        
        
        GenericJoystickButton1 = 512,
        GenericJoystickButton2,
        GenericJoystickButton3,
        GenericJoystickButton4,
        GenericJoystickButton5,
        GenericJoystickButton6,
        GenericJoystickButton7,
        GenericJoystickButton8,
        GenericJoystickButton9,
        GenericJoystickButton10,
        GenericJoystickButton11,
        GenericJoystickButton12,
        GenericJoystickButton13,
        GenericJoystickButton14,
        GenericJoystickButton15,
        GenericJoystickButton16
    }
}
